### ISSUE TITLE
Streams have problems disposing

### ISSUE THREAD

**Issue by strtdusty** [robertvazan/snappy.net#3]
Running the sample code at the bottom of your readme causes an ObjectDisposedException: Cannot access a disposed object.

using (var file = File.OpenWrite("mydata.sz"))
using (var compressor = new SnappyStream(file, CompressionMode.Compress))
using (var writer = new StreamWriter(compressor))
    writer.WriteLine("Hello World!");

`   at Snappy.SnappyStream.CheckStream()
   at Snappy.SnappyStream.EnsureCompressionMode()
   at Snappy.SnappyStream.Flush()
   at Snappy.SnappyStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at FullFrameworkSnappyTest.Program.Main(String[] args) in C:\Users\xxxx\source\repos\FullFrameworkSnappyTest\Program.cs:line 19`

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
